# Auto-update CLAUDE.md on Pull Requests
# Copy this to .github/workflows/claude-docs.yml in your project
#
# This workflow extracts patterns from PRs and can update CLAUDE.md
# Triggered by including '@.claude' in PR description

name: Update CLAUDE.md

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract-patterns:
    # Only run if PR description mentions @.claude
    if: contains(github.event.pull_request.body, '@.claude')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract code patterns from PR
        id: patterns
        run: |
          echo "Analyzing PR #${{ github.event.pull_request.number }}..."

          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Extract file patterns
          echo ""
          echo "File types modified:"
          echo "$CHANGED_FILES" | sed 's/.*\.//' | sort | uniq -c | sort -rn

          # Look for new exports/functions
          echo ""
          echo "New exports detected:"
          git diff origin/${{ github.base_ref }}...HEAD -- '*.ts' '*.tsx' '*.js' '*.jsx' | grep "^+export" | head -20 || echo "None found"

          # Look for new dependencies
          echo ""
          echo "Package.json changes:"
          git diff origin/${{ github.base_ref }}...HEAD -- 'package.json' | grep "^+" | grep -E '"[^"]+":' | head -10 || echo "No new dependencies"

      - name: Check for CLAUDE.md updates
        run: |
          if [ -f "CLAUDE.md" ]; then
            echo "CLAUDE.md exists. Consider updating with new patterns."
            echo ""
            echo "Current CLAUDE.md sections:"
            grep "^#" CLAUDE.md || echo "No headers found"
          else
            echo "No CLAUDE.md found. Consider creating one for project context."
            echo ""
            echo "Suggested CLAUDE.md structure:"
            echo "# Project Name"
            echo "## Architecture"
            echo "## Key Patterns"
            echo "## Common Commands"
          fi

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const body = `### Claude Context Analysis

            This PR was flagged for CLAUDE.md review (\`@.claude\` in description).

            **Action Required:** Review the workflow logs to see extracted patterns.

            Consider updating \`CLAUDE.md\` with:
            - New architectural patterns introduced
            - New dependencies and their purpose
            - Updated file structure conventions

            ---
            *This comment was generated automatically.*`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: body
            });

  update-docs:
    needs: extract-patterns
    runs-on: ubuntu-latest
    # Only run on PRs from maintainers (not forks)
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update last-modified date
        run: |
          if [ -f "CLAUDE.md" ]; then
            # Update last modified comment if it exists
            if grep -q "Last updated:" CLAUDE.md; then
              sed -i "s/Last updated:.*/Last updated: $(date +%Y-%m-%d)/" CLAUDE.md
            fi
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CLAUDE.md || true
          git diff --staged --quiet || git commit -m "docs: update CLAUDE.md [skip ci]"
          git push || echo "No changes to push"
